-- Laboratory 4 Section A
-- Role-Based Asset Transaction and Approval Management
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create type public.app_role as enum ('Administrator','Laboratory Staff','Requester / Viewer');
create type public.equipment_status as enum ('Available','Borrowed','Maintenance');
create type public.request_status as enum ('Pending','Approved','Rejected','Released','Returned','Overdue','Closed');
create type public.maintenance_status as enum ('Pending','In Progress','Completed');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  role public.app_role not null,
  created_at timestamptz not null default now()
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  asset_code text unique not null,
  name text not null,
  category text not null,
  location text not null,
  status public.equipment_status not null default 'Available',
  created_at timestamptz not null default now()
);

create table if not exists public.borrowing_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id),
  equipment_id bigint not null references public.equipment(id),
  purpose text not null,
  start_date date not null,
  end_date date not null,
  status public.request_status not null default 'Pending',
  approved_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valid_dates check (end_date >= start_date)
);

create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id),
  equipment_id bigint not null references public.equipment(id),
  issue text not null,
  status public.maintenance_status not null default 'Pending',
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  module text not null,
  record_id text,
  description text not null,
  created_at timestamptz not null default now()
);

create or replace function public.my_role()
returns public.app_role
language sql stable security definer set search_path=public
as $$ select role from public.profiles where id=auth.uid() $$;

alter table public.profiles enable row level security;
alter table public.equipment enable row level security;
alter table public.borrowing_requests enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read" on public.profiles for select to authenticated using (id=auth.uid() or public.my_role()='Administrator');

drop policy if exists "admin equipment all" on public.equipment;
create policy "admin equipment all" on public.equipment for all to authenticated using (public.my_role()='Administrator') with check (public.my_role()='Administrator');
drop policy if exists "authenticated equipment read" on public.equipment;
create policy "authenticated equipment read" on public.equipment for select to authenticated using (true);

drop policy if exists "requester own borrowing read" on public.borrowing_requests;
create policy "requester own borrowing read" on public.borrowing_requests for select to authenticated using (requester_id=auth.uid() or public.my_role()='Administrator' or public.my_role()='Laboratory Staff');
drop policy if exists "requester borrowing insert" on public.borrowing_requests;
create policy "requester borrowing insert" on public.borrowing_requests for insert to authenticated with check ((requester_id=auth.uid()) and (public.my_role()='Requester / Viewer' or public.my_role()='Laboratory Staff'));
drop policy if exists "admin borrowing update" on public.borrowing_requests;
create policy "admin borrowing update" on public.borrowing_requests for update to authenticated using (public.my_role()='Administrator') with check (public.my_role()='Administrator');

drop policy if exists "maintenance read" on public.maintenance_requests;
create policy "maintenance read" on public.maintenance_requests for select to authenticated using (requester_id=auth.uid() or public.my_role()='Administrator' or public.my_role()='Laboratory Staff');
drop policy if exists "staff maintenance insert" on public.maintenance_requests;
create policy "staff maintenance insert" on public.maintenance_requests for insert to authenticated with check (requester_id=auth.uid() and public.my_role()='Laboratory Staff');
drop policy if exists "admin maintenance update" on public.maintenance_requests;
create policy "admin maintenance update" on public.maintenance_requests for update to authenticated using (public.my_role()='Administrator') with check (public.my_role()='Administrator');

drop policy if exists "admin audit read" on public.audit_logs;
create policy "admin audit read" on public.audit_logs for select to authenticated using (public.my_role()='Administrator');

create or replace function public.approve_or_reject_request(p_request_id bigint,p_status public.request_status)
returns void language plpgsql security definer set search_path=public
as $$
declare r borrowing_requests%rowtype;
begin
  if public.my_role() <> 'Administrator' then raise exception 'Only Administrator may approve or reject requests'; end if;
  if p_status not in ('Approved','Rejected') then raise exception 'Invalid decision'; end if;
  select * into r from borrowing_requests where id=p_request_id for update;
  if not found then raise exception 'Request not found'; end if;
  if r.status <> 'Pending' then raise exception 'Only Pending requests may be approved or rejected'; end if;
  if r.requester_id=auth.uid() then raise exception 'Administrator cannot approve their own request'; end if;
  update borrowing_requests set status=p_status, approved_by=auth.uid(), updated_at=now() where id=p_request_id;
  insert into audit_logs(user_id,action,module,record_id,description) values(auth.uid(),upper(p_status::text),'Borrowing',p_request_id,'Administrator decision on borrowing request');
end $$;

create or replace function public.release_request(p_request_id bigint)
returns void language plpgsql security definer set search_path=public
as $$
declare r borrowing_requests%rowtype;
begin
  if public.my_role() <> 'Administrator' then raise exception 'Only Administrator may release approved requests'; end if;
  select * into r from borrowing_requests where id=p_request_id for update;
  if not found then raise exception 'Request not found'; end if;
  if r.status <> 'Approved' then raise exception 'Only Approved requests may be released'; end if;
  if exists(select 1 from equipment where id=r.equipment_id and status<>'Available') then raise exception 'Equipment is not available'; end if;
  update borrowing_requests set status='Released',updated_at=now() where id=p_request_id;
  update equipment set status='Borrowed' where id=r.equipment_id;
  insert into audit_logs(user_id,action,module,record_id,description) values(auth.uid(),'RELEASED','Borrowing',p_request_id,'Approved equipment released and marked Borrowed');
end $$;

create or replace function public.return_request(p_request_id bigint)
returns void language plpgsql security definer set search_path=public
as $$
declare r borrowing_requests%rowtype;
begin
  if public.my_role() <> 'Laboratory Staff' then raise exception 'Only Laboratory Staff may process returns'; end if;
  select * into r from borrowing_requests where id=p_request_id for update;
  if not found then raise exception 'Request not found'; end if;
  if r.status <> 'Released' then raise exception 'Only Released transactions may be returned'; end if;
  update borrowing_requests set status='Returned',updated_at=now() where id=p_request_id;
  update equipment set status='Available' where id=r.equipment_id;
  insert into audit_logs(user_id,action,module,record_id,description) values(auth.uid(),'RETURNED','Borrowing',p_request_id,'Released equipment returned and marked Available');
end $$;

create or replace function public.complete_maintenance(p_request_id bigint)
returns void language plpgsql security definer set search_path=public
as $$
declare r maintenance_requests%rowtype;
begin
  if public.my_role() <> 'Administrator' then raise exception 'Only Administrator may complete maintenance'; end if;
  select * into r from maintenance_requests where id=p_request_id for update;
  if not found then raise exception 'Maintenance request not found'; end if;
  update maintenance_requests set status='Completed' where id=p_request_id;
  update equipment set status='Available' where id=r.equipment_id;
  insert into audit_logs(user_id,action,module,record_id,description) values(auth.uid(),'MAINTENANCE_COMPLETED','Maintenance',p_request_id,'Maintenance completed and equipment returned to Available');
end $$;

-- IMPORTANT:
-- The first Administrator must be created manually once (Supabase Dashboard Authentication > Users).
-- Then insert its profile row using the generated Auth user UUID:
-- insert into public.profiles(id,full_name,email,role)
-- values('AUTH-USER-UUID','System Administrator','admin@example.com','Administrator');
--
-- After that, the web application uses the secure Edge Function to let
-- Administrator accounts create all Laboratory Staff and Requester/Viewer accounts.
